### ISSUE TITLE
v8.0.0-rc.1 doesn't report any type errors

### ISSUE THREAD

**Issue by teppeis** [bolinfest/plovr#154]
Thank you for updating closure tools!

I've tried the RC with `build` command.
I was able to generate the result source code, but did not display any type errors.

**Comment by nicks** [comment]
ya, something weird is going on, if i have a test config:

```
{
  "id": "demo",
  "inputs": "main.js",
  "checks": {
    "checkTypes": "ERROR"
  }
}
```

then typechecking doesn't do anything, but if i have:

```
{
  "id": "demo",
  "inputs": "main.js",
  "language-in": "ECMASCRIPT5",
  "checks": {
    "checkTypes": "ERROR"
  }
}
```

then typechecking catches errors again. hmmm....

**Comment by nicks** [comment]
I filed a bug upstream as https://github.com/google/closure-compiler/issues/3016

Let's see what they say. Their response will determine the best way to work around this. It looks like a bug in the options API that they didn't notice because the closure-compiler CLI is hacking around it.

If you want to continue using the RC, you can try to set the language-out to ECMASCRIPT5

**Comment by teppeis** [comment]
@nicks Thank you! I got it.
Closure Compiler doesn't seems to support type checking without transpilation to ES5.
How about changing the default language-out of plovr to ECMASCRIPT5 according to Closure Compiler CLI?

**Comment by nicks** [comment]
fixed in https://github.com/bolinfest/plovr/pull/156
