### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ambar** [bolinfest/plovr#81]
foo.dev html: 

```html
<script src="http://localhost:9810/compile?id=:id"></script>
```

Error:
>  XMLHttpRequest cannot load `http://localhost:9810/module/:id/:module`. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin `'http://foo.dev'` is therefore not allowed access.

**Comment by atannus** [comment]
I ran into this a while ago. It is related to whether Chrome loads JS files
with <script> vs XHR (see code comments).

Perhaps your issue is the same as mine, which I fixed  with the following
override to a *moduleLoader* method.

//# !!HACK!! (atannus)
//# moduleLoader.setDebugMode(true) used to be enough to cause <script> tags
//# instead of XHR loading method, but it is no longer enough in CHORME.
//# This override fixes the issue (ALLOW-ORIGIN) until plovr provides
//# CORS-enabled serving of files.
//# See https://code.google.com/p/plovr/issues/detail?id=62
if( goog.DEBUG ) {
moduleLoader.usingSourceUrlInjection_ = function(){return false;};
}

-- 
André Tannús | Epungo | +55 11 2389-4360
We are a layer
